---
# Practica Hospitales

A partir del CSV hospitales2.csv, generar un archivo CSV de salida, que contenga los siguientes campos en este orden:
* latitude
* longitude
* name
* label

Con los correspondientes datos extraídos del CSV original, el campo name tiene que corresponder con la dirección del hospital, y el campo label con el nombre del hospital.

---

In [18]:
import pandas as pd

df = pd.read_csv("hospitales2.csv")

df.head()

,WKT,ID,NOMBRE,NOM_MAP,OBJETO,CALLE,ALTURA,DOM_NORMA,DOM_GEO,TELEFONO,GUARDIA,FAX,WEB,COD_POSTAL,TIPO,TIPO_ESPEC,MOD_AT_1,MOD_AT_2,DEPEND_ADM,DIRECTOR
0,POINT (-58.3775508488443 -34.6288473603881),1.0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,HOSP. DE ELIZALDE,HOSPITAL,MANUEL A. MONTES DE OCA,40,"MONTES DE OCA, MANUEL AV. 40","40 MONTES DE OCA, MANUEL AV.",4307-5842 / 5844,4307-5442 / 4300-1700,4302-7400,www.elizalde.gov.ar,C1270AAN,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Javier Indart
1,POINT (-58.4120700769456 -34.5941919726393),2.0,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,HOSP. GUTIERREZ,HOSPITAL,GALLO,1330,GALLO 1330,1330 GALLO,4962-9247 / 9248 / 9280,4962-9232,4962-3762,www.guti.gov.ar,C1425EFD,Hospital de niños,PEDIATRIA,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. María Cristina Galoppo
2,POINT (-58.4027276547828 -34.5845283357505),4.0,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,HOSP. ODONTOLOGICO CARRILLO,HOSPITAL,SANCHEZ DE BUSTAMANTE,2529,SANCHEZ DE BUSTAMANTE 2529,2529 SANCHEZ DE BUSTAMANTE,4805-5521 / 7533,4805-6407,4805-7533,NaN,C1425DUY,Hospital especializado,ODONTOLOGIA,AT. AMBULATORIA,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Susana Rita Lisanti
3,POINT (-58.3851559118889 -34.6394041316484),6.0,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,HOSP. MOYANO,HOSPITAL,BRANDSEN,2570,BRANDSEN 2570,2570 BRANDSEN,4301-3655 / 3659,4301-4522,4303-3655/59,www.moyano.org.ar,C1287ABJ,Hospital especializado,SALUD MENTAL,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dra. Norma Derito
4,POINT (-58.3913114406535 -34.6341535760002),7.0,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,HOSP. UDAONDO,HOSPITAL,CASEROS,2061,CASEROS AV. 2061,2061 CASEROS AV.,4306-4641 al 4649,4306-4641 al 49 (int. 125),4306-3013,NaN,C1264AAA,Hospital especializado,ENF. APAR. DIGESTIVO,AT. AMB./INTERNACION,DIAG./TRATAM.,Ministerio de Salud GCBA,Dr. Eduardo Gustavo Sosa

---
#### Recuperamos cantidad de registros, cantidad de columnas, nombre de las columnas

---

In [19]:
n_rows, n_cols = df.shape
cols = list(df.columns)
sep = "-------------------------------------------------------------------------------------"
print(sep)
print("Cantidad de columnas (features) --> ", n_cols)
print(sep)
print("Cantidad de filas --> ", n_rows)
print(sep)
print("Nombre de las columnas --> \n", cols)
print(sep)

-------------------------------------------------------------------------------------
Cantidad de columnas (features) -->  20
-------------------------------------------------------------------------------------
Cantidad de filas -->  36
-------------------------------------------------------------------------------------
Nombre de las columnas -->
 ['WKT', 'ID', 'NOMBRE', 'NOM_MAP', 'OBJETO', 'CALLE', 'ALTURA', 'DOM_NORMA', 'DOM_GEO', 'TELEFONO', 'GUARDIA', 'FAX', 'WEB', 'COD_POSTAL', 'TIPO', 'TIPO_ESPEC', 'MOD_AT_1', 'MOD_AT_2', 'DEPEND_ADM', 'DIRECTOR']
-------------------------------------------------------------------------------------

---
#### La informacion que necesitamos se encuentra en algunas columnas

Necesitamos las siguientes columnas:
* WKT
* NOMBRE
* CALLE
* ALTURA

---

#### Generamos un nuevo dataframe, solo con las columnas necesarias

---

In [24]:
df2 = df[["WKT", "NOMBRE", "CALLE", "ALTURA"]]
df2.head()

,WKT,NOMBRE,CALLE,ALTURA
0,POINT (-58.3775508488443 -34.6288473603881),HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,MANUEL A. MONTES DE OCA,40
1,POINT (-58.4120700769456 -34.5941919726393),HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,GALLO,1330
2,POINT (-58.4027276547828 -34.5845283357505),HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,SANCHEZ DE BUSTAMANTE,2529
3,POINT (-58.3851559118889 -34.6394041316484),HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,BRANDSEN,2570
4,POINT (-58.3913114406535 -34.6341535760002),HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,CASEROS,2061

---
#### Genero dos funciones para recuperar la latitud y la longitud

---

In [21]:
str = "POINT (-58.3775508488443 -34.6288473603881)"




def getLatitud(str):
    ini = str.rfind("(")+1
    fin = str.find(")")
    lista = str[ini:fin].split(" ")
    latitud = float(lista[0])
    

    return latitud

def getLongitud(str):
    ini = str.rfind("(")+1
    fin = str.find(")")
    lista = str[ini:fin].split(" ")    
    longitud = float(lista[1])
    return longitud


getLatitud(str)

-58.3775508488443

---
#### Creamos dos nuevas columnas latitud y longitud, a partir de la columna WKT utilizando las funciones previamente creadas


---

In [25]:
df2["latitud"] = df2["WKT"].apply(getLatitud)
df2["longitud"] = df2["WKT"].apply(getLongitud)

C:\Users\kuens\AppData\Local\Temp\ipykernel_2188\3161734869.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["latitud"] = df2["WKT"].apply(getLatitud)
C:\Users\kuens\AppData\Local\Temp\ipykernel_2188\3161734869.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["longitud"] = df2["WKT"].apply(getLongitud)

,WKT,NOMBRE,CALLE,ALTURA,latitud,longitud
0,POINT (-58.3775508488443 -34.6288473603881),HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,MANUEL A. MONTES DE OCA,40,-58.377551,-34.628847
1,POINT (-58.4120700769456 -34.5941919726393),HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,GALLO,1330,-58.412070,-34.594192
2,POINT (-58.4027276547828 -34.5845283357505),HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,SANCHEZ DE BUSTAMANTE,2529,-58.402728,-34.584528
3,POINT (-58.3851559118889 -34.6394041316484),HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,BRANDSEN,2570,-58.385156,-34.639404
4,POINT (-58.3913114406535 -34.6341535760002),HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,CASEROS,2061,-58.391311,-34.634154

In [26]:
df2.head()

,WKT,NOMBRE,CALLE,ALTURA,latitud,longitud
0,POINT (-58.3775508488443 -34.6288473603881),HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,MANUEL A. MONTES DE OCA,40,-58.377551,-34.628847
1,POINT (-58.4120700769456 -34.5941919726393),HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,GALLO,1330,-58.412070,-34.594192
2,POINT (-58.4027276547828 -34.5845283357505),HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,SANCHEZ DE BUSTAMANTE,2529,-58.402728,-34.584528
3,POINT (-58.3851559118889 -34.6394041316484),HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,BRANDSEN,2570,-58.385156,-34.639404
4,POINT (-58.3913114406535 -34.6341535760002),HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,CASEROS,2061,-58.391311,-34.634154

---
#### Creo una nueva columna con la direccion entera (calle + altura)


---

In [30]:
df2["Name"] = df2["CALLE"]+" "+df2["ALTURA"].astype("str")

C:\Users\kuens\AppData\Local\Temp\ipykernel_2188\1123092318.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Name"] = df2["CALLE"]+" "+df2["ALTURA"].astype("str")

In [31]:
df2.head()

,WKT,NOMBRE,CALLE,ALTURA,latitud,longitud,Name
0,POINT (-58.3775508488443 -34.6288473603881),HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,MANUEL A. MONTES DE OCA,40,-58.377551,-34.628847,MANUEL A. MONTES DE OCA 40
1,POINT (-58.4120700769456 -34.5941919726393),HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,GALLO,1330,-58.412070,-34.594192,GALLO 1330
2,POINT (-58.4027276547828 -34.5845283357505),HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,SANCHEZ DE BUSTAMANTE,2529,-58.402728,-34.584528,SANCHEZ DE BUSTAMANTE 2529
3,POINT (-58.3851559118889 -34.6394041316484),HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,BRANDSEN,2570,-58.385156,-34.639404,BRANDSEN 2570
4,POINT (-58.3913114406535 -34.6341535760002),HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,CASEROS,2061,-58.391311,-34.634154,CASEROS 2061

---
#### Renombro la coluna NOMBRE a label (es lo solicitado en el enunciado)

---

In [34]:
df2.rename(columns={"NOMBRE":"label"}, inplace=True)
df2.head()

C:\Users\kuens\AppData\Local\Temp\ipykernel_2188\1320189941.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={"NOMBRE":"label"}, inplace=True)

,WKT,label,CALLE,ALTURA,latitud,longitud,Name
0,POINT (-58.3775508488443 -34.6288473603881),HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,MANUEL A. MONTES DE OCA,40,-58.377551,-34.628847,MANUEL A. MONTES DE OCA 40
1,POINT (-58.4120700769456 -34.5941919726393),HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,GALLO,1330,-58.412070,-34.594192,GALLO 1330
2,POINT (-58.4027276547828 -34.5845283357505),HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,SANCHEZ DE BUSTAMANTE,2529,-58.402728,-34.584528,SANCHEZ DE BUSTAMANTE 2529
3,POINT (-58.3851559118889 -34.6394041316484),HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,BRANDSEN,2570,-58.385156,-34.639404,BRANDSEN 2570
4,POINT (-58.3913114406535 -34.6341535760002),HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,CASEROS,2061,-58.391311,-34.634154,CASEROS 2061

---
#### Elimino las columnas que no necesito

---

In [35]:
df2 = df2.drop(["WKT", "CALLE", "ALTURA"], axis=1)
df2.head()

,label,latitud,longitud,Name
0,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,-58.377551,-34.628847,MANUEL A. MONTES DE OCA 40
1,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,-58.412070,-34.594192,GALLO 1330
2,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,-58.402728,-34.584528,SANCHEZ DE BUSTAMANTE 2529
3,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,-58.385156,-34.639404,BRANDSEN 2570
4,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,-58.391311,-34.634154,CASEROS 2061

---
#### Reordeno las columnas para que esten en el orden solicitado

---

In [36]:
df2 = df2[["latitud", "longitud", "label", "Name"]]
df2.head()

,latitud,longitud,label,Name
0,-58.377551,-34.628847,HOSPITAL GENERAL DE NIÑOS PEDRO DE ELIZALDE,MANUEL A. MONTES DE OCA 40
1,-58.412070,-34.594192,HOSPITAL GENERAL DE NIÑOS RICARDO GUTIERREZ,GALLO 1330
2,-58.402728,-34.584528,HOSPITAL DE ODONTOLOGIA DR. RAMON CARRILLO (EX...,SANCHEZ DE BUSTAMANTE 2529
3,-58.385156,-34.639404,HOSPITAL DE SALUD MENTAL BRAULIO MOYANO,BRANDSEN 2570
4,-58.391311,-34.634154,HOSPITAL DE GASTROENTEROLOGIA B. UDAONDO,CASEROS 2061

---
#### Finalmente guardo el dataframe en un archivo .csv (separado por comas)

---

In [38]:
df2.to_csv("hospital_procesado_noe.csv", sep=",", index=False)